Anonymous message feature (#136)
* Add coins and exp to user when they stay in voice channel

* Resolve Eslint error

* Rename money to coins

* Add try catch

* Update Curse

* Fix errors on developer-guides.md example code

* New feature: send notification to all guilds by super user

* Fix bug:
New member does not create a new user that cause error:
PrismaClientKnownRequestError: Foreign key constraint failed on the field: `Member_userID_fkey

Now fixed

* Change Color for embed

* Logger info instead of console.log

* Working on anonymous message

* Anonymous message feature